
// Only register if C++20 is available
#if __cplusplus >= 202002L

// Generated by cppally: do not edit by hand
// clang-format off

#include <cppally/r_dispatch.h>
#include <cppally.hpp>
#include <R_ext/Visibility.h>

using namespace cppally;
using internal::cpp_to_r;
using internal::r_to_cpp;
using internal::dispatch_template_impl;

// R-registered flag to check whether C++20 is available
SEXP cpp20_available();
extern "C" SEXP _cpp20_available() {
  return Rf_ScalarLogical(1);
}

// chi_check.cpp
r_vector<r_str> cpp_chi_check(const r_vector<r_str>& x, bool check_mod11, bool check_mod10);
extern "C" SEXP _phsmethods_cpp_chi_check(SEXP x, SEXP check_mod11, SEXP check_mod10) {
  BEGIN_CPPALLY
  return cpp_to_r(::cpp_chi_check(r_to_cpp<const r_vector<r_str>&>(x), r_to_cpp<bool>(check_mod11), r_to_cpp<bool>(check_mod10)));
  END_CPPALLY
}
// dob_from_chi.cpp
r_vector<r_date> cpp_dob_from_chi(const r_vector<r_str>& x, const r_vector<r_date>& min_date, const r_vector<r_date>& max_date);
extern "C" SEXP _phsmethods_cpp_dob_from_chi(SEXP x, SEXP min_date, SEXP max_date) {
  BEGIN_CPPALLY
  return cpp_to_r(::cpp_dob_from_chi(r_to_cpp<const r_vector<r_str>&>(x), r_to_cpp<const r_vector<r_date>&>(min_date), r_to_cpp<const r_vector<r_date>&>(max_date)));
  END_CPPALLY
}

#else

// When C++20 is not available, register dummy functions
// to satisfy R CMD checks on symbol lookup and routine registrations.
// We use the R function cpp20_available() to check whether the C++ functions
// can be safely called.

#include <Rinternals.h>
#include <R_ext/Visibility.h>

// R-registered flag to check whether C++20 is available
SEXP cpp20_available();
extern "C" SEXP _cpp20_available() {
  return Rf_ScalarLogical(0);
}

SEXP cpp_chi_check(SEXP x, SEXP check_mod11, SEXP check_mod10);
extern "C" SEXP _phsmethods_cpp_chi_check(SEXP x, SEXP check_mod11, SEXP check_mod10) {
  Rf_error("Internal error: use `phsmethods::chi_check()`");
  return R_NilValue; // Unreachable but satisfies SEXP return type
}

SEXP cpp_dob_from_chi(SEXP x, SEXP min_date, SEXP max_date);
extern "C" SEXP _phsmethods_cpp_dob_from_chi(SEXP x, SEXP min_date, SEXP max_date) {
  Rf_error("Internal error: use `phsmethods::dob_from_chi()`");
  return R_NilValue; // Unreachable but satisfies SEXP return type
}

#endif

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_cpp20_available",             (DL_FUNC) &_cpp20_available,             0},
    {"_phsmethods_cpp_chi_check",    (DL_FUNC) &_phsmethods_cpp_chi_check,    3},
    {"_phsmethods_cpp_dob_from_chi", (DL_FUNC) &_phsmethods_cpp_dob_from_chi, 3},
    {NULL, NULL, 0}
};
}


extern "C" attribute_visible void R_init_phsmethods(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}

